2022-02-18 15:26:07,137 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-18 15:40:16,537 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-18 15:40:18,231 ERROR: Exception on /userlist [GET] [in D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Users\Simon\Python-VSCode\projects\Microblog\app\routes.py", line 103, in userlist
    users = User.query()
TypeError: 'BaseQuery' object is not callable
2022-02-18 15:42:00,821 ERROR: Exception on /userlist [GET] [in D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Users\Simon\Python-VSCode\projects\Microblog\app\routes.py", line 103, in userlist
    users = User.all()
TypeError: 'BaseQuery' object is not callable
2022-02-18 15:44:57,551 ERROR: Exception on /userlist [GET] [in D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Users\Simon\Python-VSCode\projects\Microblog\app\routes.py", line 103, in userlist
    users = User.query.all()
TypeError: 'BaseQuery' object is not callable
2022-02-18 15:46:51,324 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-18 15:49:00,304 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-18 15:51:10,982 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-19 13:24:22,340 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-19 13:46:25,458 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
