2022-02-18 15:26:07,137 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-18 15:40:16,537 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-18 15:40:18,231 ERROR: Exception on /userlist [GET] [in D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Users\Simon\Python-VSCode\projects\Microblog\app\routes.py", line 103, in userlist
    users = User.query()
TypeError: 'BaseQuery' object is not callable
2022-02-18 15:42:00,821 ERROR: Exception on /userlist [GET] [in D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Users\Simon\Python-VSCode\projects\Microblog\app\routes.py", line 103, in userlist
    users = User.all()
TypeError: 'BaseQuery' object is not callable
2022-02-18 15:44:57,551 ERROR: Exception on /userlist [GET] [in D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\Simon\Python-VSCode\venvs\Microblogvenv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Users\Simon\Python-VSCode\projects\Microblog\app\routes.py", line 103, in userlist
    users = User.query.all()
TypeError: 'BaseQuery' object is not callable
2022-02-18 15:46:51,324 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-18 15:49:00,304 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-18 15:51:10,982 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-19 13:24:22,340 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-19 13:46:25,458 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-20 14:14:26,146 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-20 14:15:30,124 INFO: Microblog startup [in D:\Users\Simon\Python-VSCode\projects\Microblog\app\__init__.py:47]
2022-02-20 20:02:25,705 INFO: Microblog startup [in C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\__init__.py:47]
2022-02-24 14:36:10,447 INFO: Microblog startup [in C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\__init__.py:47]
2022-02-24 14:59:40,287 INFO: Microblog startup [in C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\__init__.py:47]
2022-03-06 08:27:31,578 INFO: Microblog startup [in C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\__init__.py:47]
2022-03-06 08:33:25,141 INFO: Microblog startup [in C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\__init__.py:49]
2022-03-06 08:36:42,127 INFO: Microblog startup [in C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\__init__.py:49]
2022-03-06 08:38:20,536 INFO: Microblog startup [in C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\__init__.py:49]
2022-03-06 08:38:41,064 ERROR: Exception on /login [GET] [in C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\routes.py", line 55, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\templates\base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\Simon\Documents\VSCode\MicroblogTutorial\app\templates\login.html", line 15, in block 'app_content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Simon\Documents\VSCode\venvs\myvenv\lib\site-packages\werkzeug\routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
